### ISSUE TITLE
Fund wallet crashes the app if no internet connection available

### ISSUE THREAD

**Issue by DanielPollithy** [DanielPollithy/flashwifi#56]

**Comment by DanielPollithy** [comment]
Same thing happens in withdrawal

**Comment by tobywoerthle** [comment]
@DanielPollithy I'm unable to reproduce the issue on my Android 6.0 phone, it shows the cached 0i. On my Android 8.1.0 phone, it's taking a bit longer to find the 0i, it keeps retrying the connection, but it doesn't crash the app. Android 6.0 emulator also doesn't crash.

-Which version of Android are you testing on? I'll test the same in an emulator.
-Do you have Airplane mode one?

Is it still happening if you fetch the latest code? It should've been fixed with 457f202f7fcda361c05959afb00aac4c640d7f07

**Comment by DanielPollithy** [comment]
Hey @tobywoerthle !
It looks like some of the latest commits fixed the problem! :+1:
